### ISSUE TITLE
Export to my google map

### ISSUE THREAD

**Issue by imrasp** [ecmnet/MAVGCL#104]
I am searching for the way to get gps data from px4 log (ulog) either export to google map or excel file (contain lat lon alt). Is there any option in MAVGCL or tool for this case.

Thank you in advance for any kind of help.

**Comment by ecmnet** [comment]
No, not with MAVGCL, but you can use the MAVLINK related python script available from the PX4 community to start with your own implementation on this.

**Comment by mrteera** [comment]
Maybe you can try

```
pip install pyulog
```

Create a python file e.g. get_gps.py
```
from pyulog import extract_gps_dump

extract_gps_dump.main()
```

And run `python get_gps.py log.ulg`

Reference: https://github.com/PX4/pyulog
