### ISSUE TITLE
Added to PX4 user guide

### ISSUE THREAD

**Issue by hamishwillee** [ecmnet/MAVGCL#109]
Hi @ecmnet 

Great tool. I have added a link to this from the PX4 user guide in https://github.com/PX4/px4_user_guide/pull/381

This is just a short introduction to give people a "flavour" to the tool, and is based on some of the key features you list in the readme and one of the screenshots. Is there anything else you would like to see added?

**Comment by ecmnet** [comment]
@hamishwille Thanks a lot for adding MAVGCL to the PX4 guide. I agree completely with the list of features.

**Comment by hamishwillee** [comment]
Great, and thanks for the tool!
