### ISSUE TITLE
timeout reading parameter 

### ISSUE THREAD

**Issue by noob211** [ecmnet/MAVGCL#118]
when I connect with wifi module to px4  and I enter local IP of px4 mavgcl connect
ed but repeatly show "timeout reading parameter " and I see no parameter in mavgcl 
I also want to know how can I connect  mavslam to mavgcl .please help me thanks

**Comment by lfeng17** [comment]
The same problem, have you solved it?

**Comment by alireza2033** [comment]
not yet

**Comment by alireza2033** [comment]
give me ur email address to be connected on this project
