### ISSUE TITLE
Font is too small on Ubuntu

### ISSUE THREAD

**Issue by bys1123** [ecmnet/MAVGCL#119]
Love this tool, but the UI font looks  not good on Ubuntu 16.04

Screenshot:
![2019-05-14 01-12-28屏幕截图](https://user-images.githubusercontent.com/4748411/57641406-87568400-75e7-11e9-978e-d8cc9136151f.png)

**Comment by ecmnet** [comment]
You can customize the font size in [application.css](https://github.com/ecmnet/MAVGCL/blob/master/MAVGCL/src/com/comino/flight/application.css).

**Comment by bys1123** [comment]
@ecmnet Do you have any suggestion about how to set the font-face on Ubuntu? It's not sans-serif font on Ubuntu.
