### ISSUE TITLE
Bind to all local addresses, set the remote address when the app receives a heartbeat

### ISSUE THREAD

**Issue by LorenzMeier** [ecmnet/MAVGCL#12]
- [ ] Bind to all local addresses, including broadcast and loopback
- [ ] Once the first heartbeat packet is received, send back a heartbeat packet

Doing this will ensure that you can use the tool without any command line arguments or user interaction.

**Comment by ecmnet** [comment]
Closed in favor of https://github.com/ecmnet/MAVGCL/issues/14
