### ISSUE TITLE
Some logs are not graphed

### ISSUE THREAD

**Issue by justas-** [ecmnet/MAVGCL#122]
I'm using the latest Git version of MAVGCL. When trying to analyze log files, some figures are graphed as 0, even though other tools correctly show them. Missing graphs:

- Attitude - PitchRate. (Sp. PitchRate, Rate, Sp. Rate works fine).
- Radio Control - None are workings (Chan 0-3, RSSI)

**Comment by ecmnet** [comment]
I assume you used the PX4 LogFile format. For those log messages, mapping is not complete.
Please have a look into 

https://github.com/ecmnet/MAVGCL/blob/master/MAVGCL/src/com/comino/flight/model/AnalysisDataModelMetaData.xml

to enhance the mapping on your own.
