### ISSUE TITLE
build Fail(Mac os, JDK16)

### ISSUE THREAD

**Issue by min12147833** [ecmnet/MAVGCL#129]
I downloaded the code that was uploaded on GitHub and proceeded, but I can't even build it. What's the problem?

It's been hard for me for over half a year.

This is an error.
 MAVGCL % ant all
Buildfile: /Users/Downloads/MAVGCL-master/MAVGCL/build.xml

BUILD FAILED
Target "all" does not exist in the project "MAVGAnalysis". 

Total time: 0 seconds

**Comment by ecmnet** [comment]
Target should now be deploy_osx_16. Please refer to build.xml.
