### ISSUE TITLE
PixRacer updates only little data with low interval compared to PixHawk with proxy

### ISSUE THREAD

**Issue by ecmnet** [ecmnet/MAVGCL#13]
Just need to figure out what to send to PixRacer.

**Comment by LorenzMeier** [comment]
See if that fixes it for you: https://github.com/PX4/Firmware/commit/de8c4c9901391c28ee4d86c5cf026db74b6042ac

**Comment by ecmnet** [comment]
Great! That worked. I assume that it is on purpose that only a few messages are sent:

<img width="394" alt="pixracer" src="https://cloud.githubusercontent.com/assets/7580193/13030474/e2025b18-d2ac-11e5-9008-8e9ede31a3d5.png">
