### ISSUE TITLE
Connection issue with SITL

### ISSUE THREAD

**Issue by jmailloux** [ecmnet/MAVGCL#135]
Hello, I can't get MAVGAnalysis to connect to the sitl.  I am using mavproxy to route the mavlink stream to another UDP port, and I set that port up in preferences in MAVG.  QGroundControl can connect to it at that port.  This is all on my local computer (running MacOS).  I've attached a screenshot of the preferences screen.  I don't know why there are 2 boxes for ports.  I tried streaming to port 14551, and 14555.
![Screen Shot 2021-10-20 at 11 17 49 PM](https://user-images.githubusercontent.com/6007135/138205613-6626b951-96d9-4698-84f2-8e2f0fd889c0.png)
t

**Comment by ecmnet** [comment]
SITL still requires to run mavcom or mavlquac (main class startup) as a proxy currently
