### ISSUE TITLE
UDP connection issues

### ISSUE THREAD

**Issue by ecmnet** [ecmnet/MAVGCL#14]
Think of rewriting the UDP communication driver to address the following issues:

- [x] Once the first heartbeat packet is received, send back a heartbeat packet
- [x] Fix reconnection issue, when interface is removed and re-inserted from/to PC (e.g. USB-WLAN adapter)
- [x] Reduce latency when reconnecting

**Comment by LorenzMeier** [comment]
Can't connect to SITL if setting listen address to 127.0.0.1. The network API really needs to be fixed before this is ready for wider use.

**Comment by ecmnet** [comment]
I agree. SITL uses 14556 instead of 14555.

**Comment by ecmnet** [comment]
Refer to https://github.com/ecmnet/MAVComm/issues/1

**Comment by LorenzMeier** [comment]
It would be great if the app would ask on boot which IP to connect to and remember the last IP it was connected to. Then it will be really easy to have that as default. The current approach with the IP in the build file doesn't really scale.

**Comment by ecmnet** [comment]
I am currently working on some 'Preferences'. This could also cover the IP issue.

**Comment by ecmnet** [comment]
@LorenzMeier I added a preferences dialog (File -> Preferences) to setup IP address and port (Restart required). Closing this for now.
