### ISSUE TITLE
Connection established, but no data graphed

### ISSUE THREAD

**Issue by LorenzMeier** [ecmnet/MAVGCL#17]
I can see the data in the inspector, but I can't graph anything. Might well be the height issue with the UI.

<img width="1332" alt="screen shot 2016-02-15 at 10 52 17" src="https://cloud.githubusercontent.com/assets/1208119/13045183/42a21e56-d3d2-11e5-969e-41756f0c4d9e.png">

**Comment by ecmnet** [comment]
Did you press 'recording' or enabled an automatic trigger?

**Comment by LorenzMeier** [comment]
No, and it wasn't obvious I have to. I would advise to start it automatically and allow to configure it in the panel. Its like if your oscilloscope would show nothing on boot - that would be very confusing.

**Comment by ecmnet** [comment]
That's why the button is in red 😄. But I agree, will change that.

**Comment by LorenzMeier** [comment]
The button is not red. If it would have been red I would probably have seen it. Its also not obvious its related to the graph. Change "recording" to "capture". Recording means to store something to a disk, which is not happening here.

**Comment by ecmnet** [comment]
In your screenshot, the button is red. Concerning texts, feel free to create a pull and change it. For me this has quite low priority as it is a question of interpretation.

**Comment by LorenzMeier** [comment]
You're expectation bias makes the button red for you. But in fact the button is grey with a dark red font. Because you designed it you believe its very visible, but its not.

**Comment by ecmnet** [comment]
You are right. This is a grey button, accentuated with a red font. It was the accentuation, I was aiming at with a smile some lines above. A bit of a sophistry here.
