### ISSUE TITLE
Does not compile on Linux

### ISSUE THREAD

**Issue by trondhindenes** [ecmnet/MAVGCL#22]
I'm getting loads of build errors trying to run this on Linux, the first being 
[javac] /home/trond/MAVGCL/MAVGCL/src/com/comino/flight/tabs/FlightTabs.java:63: 
error: ')' expected

**Comment by ecmnet** [comment]
Just did a clean and recompile. Everything is fine. Retry cloning, I would say.

**Comment by ecmnet** [comment]
Did you use Java 8? It is required for lambdas.

**Comment by trondhindenes** [comment]
Yup, java 8 fixed it. I ran: 
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-8-jdk

**Comment by ecmnet** [comment]
Perfect. I didn't test it with openjdk.
