### ISSUE TITLE
Screen layout is not updating (things are hardcoded to the author's screen size)

### ISSUE THREAD

**Issue by LorenzMeier** [ecmnet/MAVGCL#3]
This is currently unusable on any other screen than your own 8). It would be great if you could add the required layout to the top level window so it changes with screen size.

**Comment by ecmnet** [comment]
I'll think about it how to layout the widgets in case of resizing...

**Comment by ecmnet** [comment]
Horizontal resize enabled; vertical size reduced to fit most screens.

**Comment by LorenzMeier** [comment]
The horizontal resize helps, but I still can't reach the controls on the bottom. It needs both to be fully usable.

**Comment by ecmnet** [comment]
Saw your screen in the other issue. I think i will resize graph display, but not left-side panels

**Comment by ecmnet** [comment]
Basically fixed
