### ISSUE TITLE
Building infrastructure

### ISSUE THREAD

**Issue by dagar** [ecmnet/MAVGCL#50]
@ecmnet add build/automation wishlist items here. You can assign it to me if Github will let you.
- [ ] MAVComm as submodule
- [x] ~~maven for build system and dependencies?~~ using Ant + Ivy
- [ ] remove binaries from repo (#5)
- [x] deploy jar to github releases
- [x] travis-ci deploy_osx
- [ ] remove jmavlib packages from source and use submodule instead

**Comment by dagar** [comment]
#63 for dependencies

**Comment by dagar** [comment]
#66 upload windows package to Github releases

**Comment by dagar** [comment]
Instead of dealing with git submodule annoyances I think it would be better to just host the mavcomm binary on github releases and have it grabbed by ivy.

**Comment by ecmnet** [comment]
ok
