### ISSUE TITLE
Performance issues for graph rendering

### ISSUE THREAD

**Issue by LorenzMeier** [ecmnet/MAVGCL#58]
The app pulls 200% CPU (two cores) when running on a recent MacBook Pro 13". Which means that I can't run MAVGCL + SITL on the same machine. Is there an easy way to improve the graphing performance?

**Comment by ecmnet** [comment]
Thanks for reporting. I am aware of this and currently digging into it, although I am able to run MAVGCL+SITL (JMAVSim however) on my MBP 13" (2015) without issues.

**Comment by ecmnet** [comment]
Some performance tweaks committed.

**Comment by ecmnet** [comment]
@LorenzMeier Does this work for you now with the latest release?
