### ISSUE TITLE
Appveyor Github Authentication token

### ISSUE THREAD

**Issue by dagar** [ecmnet/MAVGCL#66]
@ecmnet In order for appveyor to upload to Github releases you have to generate a token on github and give it to appveyor. I don't have access to do this.

Instructions here "GitHub authentication token" - https://www.appveyor.com/docs/deployment/github

**Comment by ecmnet** [comment]
@dagar: The encrypted token is Hq5VDnfPj9yDRim502Eyhn7rFSgjfo3TiRs2xM+qP/wm/Wav6q/XeVNIGEEdXbtN

**Comment by dagar** [comment]
Can you tell if deploy_windows is actually working on appveyor? It's not printing the output file like the other platforms.
https://ci.appveyor.com/project/ecmnet/mavgcl/build/28#L1767

**Comment by ecmnet** [comment]
No, seems to skip the install bundle step. I have no chance to get this working here on OS X. But I saw, that C:\Program Files (x86)\Inno Setup 5; should be added to the path in order to run iscc.exe

**Comment by ecmnet** [comment]
Ok, now a *.msi file is created. But I cannot test it.
