### ISSUE TITLE
Plot shows average values instead of picks

### ISSUE THREAD

**Issue by matanhavi** [ecmnet/MAVGCL#90]
Many times the user want to see the picks of some values instead of the average when the plot is zoomed out.
Add on option to show plot either on average/picks mode

**Comment by ecmnet** [comment]
Could you Share an example via uploaded log?

**Comment by ecmnet** [comment]
Datapoint are not averaged at all. If time resolution is lower than the acquisition rate of 50ms, a spike detector determines min/max. Refer to https://github.com/ecmnet/MAVGCL/blob/master/MAVGCL/src/com/comino/flight/widgets/charts/line/LineChartWidget.java#L681

**Comment by matanhavi** [comment]
for example, on some zoom you can see about 25.4 max current.
![image](https://cloud.githubusercontent.com/assets/1760878/18248602/edacfede-7381-11e6-95f4-1b1a90132e53.png)
but when zooming in you can see the 30A max:
![image](https://cloud.githubusercontent.com/assets/1760878/18248623/13fd3900-7382-11e6-95c6-5fbd7b43b1fb.png)

**Comment by ecmnet** [comment]
@matanhavi Was that during online acquisition or while analyzing a log file? Could you please share the log via http://logs.uaventure.com?

**Comment by matanhavi** [comment]
This is during importing px4Log, 
sorry, I can't send logs
