### ISSUE TITLE
Windows installer does not work on Windows 10 anymore

### ISSUE THREAD

**Issue by ecmnet** [ecmnet/MAVGCL#95]
MSI file cannot be installed on windows 10

**Comment by zozo2020** [comment]
I am also using on windows 10 and see some issues.
The latest version just open the console, but not the GUI.
And how should I "install" the program on windows 10?
Note that just putting the mavganalysis.jar doesn't work and I also must take the other JAR from the source.

**Comment by ecmnet** [comment]
There are quite a lot of dependencies. You can find them in build.xml. The installer can be found [here](https://github.com/ecmnet/MAVGCL/releases/download/V0.622/MAVGAnalysis-0.6.msi), but it is refused by Windows 10.
