### ISSUE TITLE
Connecting MAVGCL to jMAVSim remotely via WiFi

### ISSUE THREAD

**Issue by abencomo** [ecmnet/MAVGCL#98]
I have MAVGCL installed on a Mac OSX and jMAVSim on an Intel Joule running Ubuntu.  Both machines are connected on the same wifi network.  Will it be possible for MAVGCL to monitor the mavlink data broadcasted by jMAVSim?

**Comment by ecmnet** [comment]
it should work if you provide the correct IP and Port in 'Preferences'. Als an alternative you can start it via command line (java ...) with the Option --SITL if you are on localhost.

**Comment by ecmnet** [comment]
Try Version 0.625, which fixes the port preferences. There you can now specify the bind port (second port option in preferences). For local host set the SITL option in latest master.
